version: "3"

services:
  cicd:
    build: .
    container_name: cicd
    ports:
      - "3000:3000"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks:/opt/stacks
      - ./database.db:/app/database.db
