// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Repository struct {
	ID             int64
	Name           string
	Url            string
	ContainerRepo  sql.NullString
	ContainerTag   sql.NullString
	ContainerID    sql.NullString
	ComposeFile    sql.NullString
	ComposeService sql.NullString
}
